version: '3.8'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=restaurant_db
      - MYSQL_ROOT_PASSWORD=Admin@123
    ports:
      - '3307:3306'

  prisma:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma migrate dev --name init
    environment:
      - DATABASE_URL=mysql://root:Admin@123@db:3306/restaurant_db
    depends_on:
      - db
